/// Shared orbit helpers used by all symmetry group types.
///
/// These free functions implement the three core operations needed to build a
/// symmetric basis:
///
/// - [`iter_images`] — enumerate every group-orbit image of a state.
/// - [`get_refstate`] — find the orbit representative (largest image).
/// - [`check_refstate`] — find the representative *and* count how many images
///   equal the input state (the orbit norm).
use super::{LatticeElement, traits::LocalOpItem};
use crate::bitbasis::BitInt;
use num_complex::Complex;

/// Enumerate all group-orbit images of `state`.
///
/// The orbit is generated by first applying each local op (or none — the
/// identity) and then every lattice permutation, giving
/// `lattice.len() * (1 + local.len())` images in total.
pub(crate) fn iter_images<B: BitInt, L: LocalOpItem<B>>(
    lattice: &[LatticeElement],
    local: &[L],
    state: B,
) -> Vec<(B, Complex<f64>)> {
    let one = Complex::new(1.0, 0.0);
    let mut images = Vec::with_capacity(lattice.len() * (1 + local.len()));
    for lat in lattice {
        images.push(lat.apply(state, one));
    }
    for item in local {
        let (loc_state, char_) = item.apply_local(state);
        for lat in lattice {
            images.push(lat.apply(loc_state, char_));
        }
    }
    images
}

/// Return the orbit representative (largest state in the orbit) and the
/// group-character coefficient accumulated to reach it.
pub(crate) fn get_refstate<B: BitInt, L: LocalOpItem<B>>(
    lattice: &[LatticeElement],
    local: &[L],
    state: B,
) -> (B, Complex<f64>) {
    let mut best = state;
    let mut best_coeff = Complex::new(1.0, 0.0);
    for (s, c) in iter_images(lattice, local, state) {
        if s > best {
            best = s;
            best_coeff = c;
        }
    }
    (best, best_coeff)
}

/// Return the orbit representative and the orbit norm.
///
/// The norm is the number of orbit images that equal `state` (used to
/// determine whether `state` is a valid symmetric-basis representative and to
/// compute the normalisation factor).
pub(crate) fn check_refstate<B: BitInt, L: LocalOpItem<B>>(
    lattice: &[LatticeElement],
    local: &[L],
    state: B,
) -> (B, f64) {
    let mut ref_state = state;
    let mut norm = 0.0_f64;
    for (s, _) in iter_images(lattice, local, state) {
        if s > ref_state {
            ref_state = s;
        }
        if s == state {
            norm += 1.0;
        }
    }
    (ref_state, norm)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::bitbasis::{PermDitLocations, PermDitMask};
    use num_complex::Complex;

    fn one() -> Complex<f64> {
        Complex::new(1.0, 0.0)
    }

    fn minus_one() -> Complex<f64> {
        Complex::new(-1.0, 0.0)
    }

    /// Build a `LatticeElement` that applies a site permutation with
    /// character `char_` over `n_sites` sites of LHSS 2.
    fn lat(char_: Complex<f64>, perm: &[usize], n_sites: usize) -> LatticeElement {
        LatticeElement::new(char_, PermDitLocations::new(2, perm), n_sites)
    }

    /// Build a local `(Complex<f64>, PermDitMask<u32>)` op that XOR-flips the
    /// given `mask` bits with group character `char_`.
    fn local_xor(char_: Complex<f64>, mask: u32) -> (Complex<f64>, PermDitMask<u32>) {
        (char_, PermDitMask::new(mask))
    }

    // --- iter_images ---------------------------------------------------------

    #[test]
    fn iter_images_identity_lattice_only() {
        // A single identity-lattice element (perm = [0, 1]) should return
        // exactly one image equal to the original state.
        let lattice = vec![lat(one(), &[0, 1], 2)];
        let images = iter_images::<u32, (Complex<f64>, PermDitMask<u32>)>(&lattice, &[], 0b01u32);
        assert_eq!(images.len(), 1);
        assert_eq!(images[0].0, 0b01u32);
        assert_eq!(images[0].1, one());
    }

    #[test]
    fn iter_images_two_lattice_elements() {
        // Identity + cyclic-swap: lattice produces 2 images, no local ops.
        // State 0b01 → identity gives 0b01, swap([0,1]→[1,0]) gives 0b10.
        let lattice = vec![lat(one(), &[0, 1], 2), lat(one(), &[1, 0], 2)];
        let images = iter_images::<u32, (Complex<f64>, PermDitMask<u32>)>(&lattice, &[], 0b01u32);
        assert_eq!(images.len(), 2);
        let states: Vec<u32> = images.iter().map(|(s, _)| *s).collect();
        assert!(states.contains(&0b01u32));
        assert!(states.contains(&0b10u32));
    }

    #[test]
    fn iter_images_local_op_expands_orbit() {
        // Identity lattice + one XOR-flip local op: 1 lattice × (1 + 1 local)
        // = 2 images.  State 0b01 flipped by mask 0b11 gives 0b10.
        let lattice = vec![lat(one(), &[0, 1], 2)];
        let local = vec![local_xor(minus_one(), 0b11u32)];
        let images = iter_images(&lattice, &local, 0b01u32);
        assert_eq!(images.len(), 2);
        let pairs: Vec<(u32, Complex<f64>)> = images;
        assert!(pairs.iter().any(|(s, c)| *s == 0b01u32 && *c == one()));
        assert!(
            pairs
                .iter()
                .any(|(s, c)| *s == 0b10u32 && *c == minus_one())
        );
    }

    #[test]
    fn iter_images_character_accumulated() {
        // Lattice with character -1; no local ops.  The single image should
        // carry grp_char = -1.
        let lattice = vec![lat(minus_one(), &[0, 1], 2)];
        let images = iter_images::<u32, (Complex<f64>, PermDitMask<u32>)>(&lattice, &[], 0b01u32);
        assert_eq!(images[0].1, minus_one());
    }

    // --- get_refstate --------------------------------------------------------

    #[test]
    fn get_refstate_returns_max() {
        // State 0b01; with swap lattice the orbit is {0b01, 0b10}. Max is 0b10.
        let lattice = vec![lat(one(), &[0, 1], 2), lat(one(), &[1, 0], 2)];
        let (ref_s, _) =
            get_refstate::<u32, (Complex<f64>, PermDitMask<u32>)>(&lattice, &[], 0b01u32);
        assert_eq!(ref_s, 0b10u32);
    }

    #[test]
    fn get_refstate_already_max_unchanged() {
        // State 0b10 is already the max; representative should be itself.
        let lattice = vec![lat(one(), &[0, 1], 2), lat(one(), &[1, 0], 2)];
        let (ref_s, _) =
            get_refstate::<u32, (Complex<f64>, PermDitMask<u32>)>(&lattice, &[], 0b10u32);
        assert_eq!(ref_s, 0b10u32);
    }

    #[test]
    fn get_refstate_coeff_from_winning_image() {
        // Swap lattice has character -1; state 0b01 maps to 0b10 (max).
        // The winning coefficient should be -1.
        let lattice = vec![lat(one(), &[0, 1], 2), lat(minus_one(), &[1, 0], 2)];
        let (ref_s, coeff) =
            get_refstate::<u32, (Complex<f64>, PermDitMask<u32>)>(&lattice, &[], 0b01u32);
        assert_eq!(ref_s, 0b10u32);
        assert_eq!(coeff, minus_one());
    }

    // --- check_refstate ------------------------------------------------------

    #[test]
    fn check_refstate_norm_counts_self_images() {
        // Identity lattice only: single image equals input → norm = 1.
        let lattice = vec![lat(one(), &[0, 1], 2)];
        let (_, norm) =
            check_refstate::<u32, (Complex<f64>, PermDitMask<u32>)>(&lattice, &[], 0b01u32);
        assert_eq!(norm, 1.0);
    }

    #[test]
    fn check_refstate_z2_orbit_max_norm2() {
        // Two-site Z₂: identity + swap. State 0b11 maps to itself under both
        // → norm = 2 (both images equal the input). It is also the max.
        let lattice = vec![lat(one(), &[0, 1], 2), lat(one(), &[1, 0], 2)];
        let (ref_s, norm) =
            check_refstate::<u32, (Complex<f64>, PermDitMask<u32>)>(&lattice, &[], 0b11u32);
        assert_eq!(ref_s, 0b11u32);
        assert_eq!(norm, 2.0);
    }

    #[test]
    fn check_refstate_non_max_norm1() {
        // State 0b01: swap maps it to 0b10 (≠ 0b01), identity maps to 0b01.
        // Norm = 1, representative = 0b10.
        let lattice = vec![lat(one(), &[0, 1], 2), lat(one(), &[1, 0], 2)];
        let (ref_s, norm) =
            check_refstate::<u32, (Complex<f64>, PermDitMask<u32>)>(&lattice, &[], 0b01u32);
        assert_eq!(ref_s, 0b10u32);
        assert_eq!(norm, 1.0);
    }
}
