repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        args: ["--unsafe"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: isort
        name: isort (python)
        entry: uv run --locked isort
        language: system
        types: [python]
      - id: black
        name: black
        entry: uv run --locked black
        language: system
        types: [python]
      - id: ruff
        name: ruff
        entry: uv run --locked ruff check
        language: system
        types: [python]
      - id: pyright-check
        name: pyright-check
        entry: uv run --locked pyright python
        language: system
        pass_filenames: false
        always_run: true
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all --
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy -p quspin-core -p quspin-py --all-targets -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
