/// Shared orbit helpers used by all symmetry group types.
///
/// - [`iter_images`] — enumerate every group-orbit image of a state (scalar).
/// - [`get_refstate`] — find the orbit representative (scalar).
/// - [`check_refstate`] — find the representative and orbit norm (scalar).
/// - [`check_refstate_batch`] — batch variant of `check_refstate` structured
///   for auto-vectorisation across a slice of states.
use super::lattice::{LatEl, LocalOpItem};
use num_complex::Complex;
use quspin_bitbasis::BitInt;
use smallvec::SmallVec;

/// Inline capacity for the orbit image buffer.
///
/// Covers the common cases without heap allocation:
/// - 4-site translation × 1 local op  =  8 images
/// - 8-site translation × 1 local op  = 16 images
/// - 32-site translation × 1 local op = 64 images
const ORBIT_INLINE_CAP: usize = 512;

// ---------------------------------------------------------------------------
// Scalar helpers
// ---------------------------------------------------------------------------

/// Enumerate all group-orbit images of `state`.
///
/// The orbit is generated by first applying each local op (or none — the
/// identity) and then every lattice permutation, giving
/// `lattice.len() * (1 + local.len())` images in total.
///
/// Returns a stack-allocated [`SmallVec`] that avoids heap allocation for
/// orbits up to [`ORBIT_INLINE_CAP`] elements.
pub(crate) fn iter_images<B: BitInt, E: LatEl<B>, L: LocalOpItem<B>>(
    lattice: &[E],
    local: &[L],
    state: B,
) -> SmallVec<[(B, Complex<f64>); ORBIT_INLINE_CAP]> {
    let mut images = SmallVec::new();
    for lat in lattice {
        let s = lat.apply_state(state);
        let c = lat.grp_char_for(state);
        images.push((s, c));
    }
    for item in local {
        let (loc_state, char_) = item.apply_local(state);
        for lat in lattice {
            let s = lat.apply_state(loc_state);
            let c = char_ * lat.grp_char_for(loc_state);
            images.push((s, c));
        }
    }
    images
}

/// Return the orbit representative (largest state in the orbit) and the
/// group-character coefficient accumulated to reach it.
pub(crate) fn get_refstate<B: BitInt, E: LatEl<B>, L: LocalOpItem<B>>(
    lattice: &[E],
    local: &[L],
    state: B,
) -> (B, Complex<f64>) {
    let mut best = state;
    let mut best_coeff = Complex::new(1.0, 0.0);
    for (s, c) in iter_images(lattice, local, state) {
        let cond = s > best;
        best = best.max(s);
        best_coeff = if cond { c } else { best_coeff };
    }
    (best, best_coeff)
}

/// Batch variant of [`get_refstate`], structured for loop amortisation.
///
/// For each element of `states`, finds the orbit representative (largest
/// state) and the group-character coefficient accumulated to reach it,
/// writing `(representative, grp_char)` into the corresponding element of
/// `out`.  The loop order places orbit elements in the outer loop and states
/// in the inner loop, amortising the orbit traversal across the batch.
///
/// # Panics
///
/// Panics if `states.len() != out.len()`.
pub(crate) fn get_refstate_batch<B: BitInt, E: LatEl<B>, L: LocalOpItem<B>>(
    lattice: &[E],
    local: &[L],
    states: &[B],
    out: &mut [(B, Complex<f64>)],
) {
    let n = states.len();
    assert_eq!(n, out.len());

    // Initialise: each state is its own representative with identity character.
    for (state, o) in states.iter().zip(out.iter_mut()) {
        o.0 = *state;
        o.1 = Complex::new(1.0, 0.0);
    }

    // Lattice-only images.
    for lat in lattice {
        for (state, o) in states.iter().zip(out.iter_mut()) {
            let s = lat.apply_state(*state);
            let c = lat.grp_char_for(*state);
            let cond = s > o.0;
            o.0 = o.0.max(s);
            o.1 = if cond { c } else { o.1 };
        }
    }

    // Local-then-lattice images.
    if !local.is_empty() {
        let mut loc_states = vec![B::from_u64(0); n];
        let mut loc_chars = vec![Complex::new(0.0_f64, 0.0_f64); n];
        for item in local {
            for ((state, loc), lc) in states
                .iter()
                .zip(loc_states.iter_mut())
                .zip(loc_chars.iter_mut())
            {
                let (ls, lchar) = item.apply_local(*state);
                *loc = ls;
                *lc = lchar;
            }
            for lat in lattice {
                for ((loc, lc), o) in loc_states.iter().zip(loc_chars.iter()).zip(out.iter_mut()) {
                    let s = lat.apply_state(*loc);
                    let c = *lc * lat.grp_char_for(*loc);
                    let cond = s > o.0;
                    o.0 = o.0.max(s);
                    o.1 = if cond { c } else { o.1 };
                }
            }
        }
    }
}

/// Return the orbit representative and the orbit norm.
///
/// The norm is the number of orbit images that equal `state` (used to
/// determine whether `state` is a valid symmetric-basis representative and to
/// compute the normalisation factor).
pub(crate) fn check_refstate<B: BitInt, E: LatEl<B>, L: LocalOpItem<B>>(
    lattice: &[E],
    local: &[L],
    state: B,
) -> (B, f64) {
    let mut ref_state = state;
    let mut norm = 0u32;
    for (s, _) in iter_images(lattice, local, state) {
        ref_state = ref_state.max(s);
        norm += (s == state) as u32;
    }
    (ref_state, norm as f64)
}

// ---------------------------------------------------------------------------
// Batch helper
// ---------------------------------------------------------------------------

/// Batch variant of [`check_refstate`], structured for auto-vectorisation.
///
/// Processes `states.len()` states in one call, writing `(representative,
/// norm)` for each into `out`.  The loop order is rearranged so that the
/// innermost loop iterates over the batch of states rather than over the
/// orbit elements: each orbit element (lattice permutation or local op) is
/// applied uniformly to the whole batch, enabling the compiler to emit SIMD
/// instructions for `u32`/`u64` state types.
///
/// # Panics
///
/// Panics if `states.len() != out.len()`.
pub(crate) fn check_refstate_batch<B: BitInt, E: LatEl<B>, L: LocalOpItem<B>>(
    lattice: &[E],
    local: &[L],
    states: &[B],
    out: &mut [(B, f64)],
) {
    let n = states.len();
    assert_eq!(n, out.len());

    // Initialise representatives; norms start at zero.
    for (state, o) in states.iter().zip(out.iter_mut()) {
        o.0 = *state;
    }
    let mut norms = vec![0u32; n];

    // Lattice-only images: apply each lattice element to the whole batch.
    for lat in lattice {
        for ((state, o), norm) in states.iter().zip(out.iter_mut()).zip(norms.iter_mut()) {
            let s = lat.apply_state(*state);
            o.0 = o.0.max(s);
            *norm += (s == *state) as u32;
        }
    }

    // Local-then-lattice images.
    if !local.is_empty() {
        let mut loc_states: Vec<B> = vec![B::from_u64(0); n];
        for item in local {
            for (state, loc) in states.iter().zip(loc_states.iter_mut()) {
                let (ls, _) = item.apply_local(*state);
                *loc = ls;
            }
            for lat in lattice {
                for (((loc, state), o), norm) in loc_states
                    .iter()
                    .zip(states.iter())
                    .zip(out.iter_mut())
                    .zip(norms.iter_mut())
                {
                    let s = lat.apply_state(*loc);
                    o.0 = o.0.max(s);
                    *norm += (s == *state) as u32;
                }
            }
        }
    }

    // Write norms as f64 in a single final pass.
    for (o, norm) in out.iter_mut().zip(norms.iter()) {
        o.1 = *norm as f64;
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lattice::LatticeElement;
    use num_complex::Complex;
    use quspin_bitbasis::{PermDitLocations, PermDitMask};

    fn one() -> Complex<f64> {
        Complex::new(1.0, 0.0)
    }

    fn minus_one() -> Complex<f64> {
        Complex::new(-1.0, 0.0)
    }

    /// Build a `LatticeElement` that applies a site permutation with
    /// character `char_` over `n_sites` sites of LHSS 2.
    fn lat(char_: Complex<f64>, perm: &[usize], n_sites: usize) -> LatticeElement {
        LatticeElement::new(char_, PermDitLocations::new(2, perm), n_sites)
    }

    /// Build a local `(Complex<f64>, PermDitMask<u32>)` op that XOR-flips the
    /// given `mask` bits with group character `char_`.
    fn local_xor(char_: Complex<f64>, mask: u32) -> (Complex<f64>, PermDitMask<u32>) {
        (char_, PermDitMask::new(mask))
    }

    // --- iter_images ---------------------------------------------------------

    #[test]
    fn iter_images_identity_lattice_only() {
        let lattice = vec![lat(one(), &[0, 1], 2)];
        let images = iter_images::<u32, LatticeElement, (Complex<f64>, PermDitMask<u32>)>(
            &lattice,
            &[],
            0b01u32,
        );
        assert_eq!(images.len(), 1);
        assert_eq!(images[0].0, 0b01u32);
        assert_eq!(images[0].1, one());
    }

    #[test]
    fn iter_images_two_lattice_elements() {
        let lattice = vec![lat(one(), &[0, 1], 2), lat(one(), &[1, 0], 2)];
        let images = iter_images::<u32, LatticeElement, (Complex<f64>, PermDitMask<u32>)>(
            &lattice,
            &[],
            0b01u32,
        );
        assert_eq!(images.len(), 2);
        let states: Vec<u32> = images.iter().map(|(s, _)| *s).collect();
        assert!(states.contains(&0b01u32));
        assert!(states.contains(&0b10u32));
    }

    #[test]
    fn iter_images_local_op_expands_orbit() {
        let lattice = vec![lat(one(), &[0, 1], 2)];
        let local = vec![local_xor(minus_one(), 0b11u32)];
        let images = iter_images(&lattice, &local, 0b01u32);
        assert_eq!(images.len(), 2);
        let pairs: Vec<(u32, Complex<f64>)> = images.into_vec();
        assert!(pairs.iter().any(|(s, c)| *s == 0b01u32 && *c == one()));
        assert!(
            pairs
                .iter()
                .any(|(s, c)| *s == 0b10u32 && *c == minus_one())
        );
    }

    #[test]
    fn iter_images_character_accumulated() {
        let lattice = vec![lat(minus_one(), &[0, 1], 2)];
        let images = iter_images::<u32, LatticeElement, (Complex<f64>, PermDitMask<u32>)>(
            &lattice,
            &[],
            0b01u32,
        );
        assert_eq!(images[0].1, minus_one());
    }

    // --- get_refstate --------------------------------------------------------

    #[test]
    fn get_refstate_returns_max() {
        let lattice = vec![lat(one(), &[0, 1], 2), lat(one(), &[1, 0], 2)];
        let (ref_s, _) = get_refstate::<u32, LatticeElement, (Complex<f64>, PermDitMask<u32>)>(
            &lattice,
            &[],
            0b01u32,
        );
        assert_eq!(ref_s, 0b10u32);
    }

    #[test]
    fn get_refstate_already_max_unchanged() {
        let lattice = vec![lat(one(), &[0, 1], 2), lat(one(), &[1, 0], 2)];
        let (ref_s, _) = get_refstate::<u32, LatticeElement, (Complex<f64>, PermDitMask<u32>)>(
            &lattice,
            &[],
            0b10u32,
        );
        assert_eq!(ref_s, 0b10u32);
    }

    #[test]
    fn get_refstate_coeff_from_winning_image() {
        let lattice = vec![lat(one(), &[0, 1], 2), lat(minus_one(), &[1, 0], 2)];
        let (ref_s, coeff) = get_refstate::<u32, LatticeElement, (Complex<f64>, PermDitMask<u32>)>(
            &lattice,
            &[],
            0b01u32,
        );
        assert_eq!(ref_s, 0b10u32);
        assert_eq!(coeff, minus_one());
    }

    // --- check_refstate ------------------------------------------------------

    #[test]
    fn check_refstate_norm_counts_self_images() {
        let lattice = vec![lat(one(), &[0, 1], 2)];
        let (_, norm) = check_refstate::<u32, LatticeElement, (Complex<f64>, PermDitMask<u32>)>(
            &lattice,
            &[],
            0b01u32,
        );
        assert_eq!(norm, 1.0);
    }

    #[test]
    fn check_refstate_z2_orbit_max_norm2() {
        let lattice = vec![lat(one(), &[0, 1], 2), lat(one(), &[1, 0], 2)];
        let (ref_s, norm) = check_refstate::<u32, LatticeElement, (Complex<f64>, PermDitMask<u32>)>(
            &lattice,
            &[],
            0b11u32,
        );
        assert_eq!(ref_s, 0b11u32);
        assert_eq!(norm, 2.0);
    }

    #[test]
    fn check_refstate_non_max_norm1() {
        let lattice = vec![lat(one(), &[0, 1], 2), lat(one(), &[1, 0], 2)];
        let (ref_s, norm) = check_refstate::<u32, LatticeElement, (Complex<f64>, PermDitMask<u32>)>(
            &lattice,
            &[],
            0b01u32,
        );
        assert_eq!(ref_s, 0b10u32);
        assert_eq!(norm, 1.0);
    }

    // --- check_refstate_batch ------------------------------------------------

    #[test]
    fn batch_matches_scalar_lattice_only() {
        // Batch result must equal scalar result for every state.
        let lattice = vec![lat(one(), &[0, 1], 2), lat(one(), &[1, 0], 2)];
        let local = vec![] as Vec<(Complex<f64>, PermDitMask<u32>)>;
        let states: Vec<u32> = (0u32..4).collect();
        let mut out = vec![(0u32, 0.0); states.len()];
        check_refstate_batch(&lattice, &local, &states, &mut out);
        for (state, (batch_ref, batch_norm)) in states.iter().zip(out.iter()) {
            let (scalar_ref, scalar_norm) = check_refstate(&lattice, &local, *state);
            assert_eq!(
                *batch_ref, scalar_ref,
                "ref mismatch for state {state:#04b}"
            );
            assert_eq!(
                *batch_norm, scalar_norm,
                "norm mismatch for state {state:#04b}"
            );
        }
    }

    #[test]
    fn batch_matches_scalar_with_local_op() {
        // With a flip local op, batch and scalar must still agree.
        let lattice = vec![lat(one(), &[0, 1], 2)];
        let local = vec![local_xor(one(), 0b11u32)];
        let states: Vec<u32> = (0u32..4).collect();
        let mut out = vec![(0u32, 0.0); states.len()];
        check_refstate_batch(&lattice, &local, &states, &mut out);
        for (state, (batch_ref, batch_norm)) in states.iter().zip(out.iter()) {
            let (scalar_ref, scalar_norm) = check_refstate(&lattice, &local, *state);
            assert_eq!(
                *batch_ref, scalar_ref,
                "ref mismatch for state {state:#04b}"
            );
            assert_eq!(
                *batch_norm, scalar_norm,
                "norm mismatch for state {state:#04b}"
            );
        }
    }

    #[test]
    fn batch_empty_input_is_noop() {
        let lattice = vec![lat(one(), &[0, 1], 2)];
        let local = vec![] as Vec<(Complex<f64>, PermDitMask<u32>)>;
        let mut out: Vec<(u32, f64)> = vec![];
        check_refstate_batch(&lattice, &local, &[], &mut out); // must not panic
    }
}
