//! Internal macros that generate the inherent-impl `match-and-delegate`
//! methods on each level of the dispatch hierarchy.
//!
//! Three levels:
//!
//! 1. Per-size **inner** enums (`BitBasisDefault` /
//!    `BitBasisLargeInt` and the analogous Trit / Quat / Dit
//!    pairs) — actual concrete variants. Generated by
//!    [`impl_inner_dispatch_enum!`]; methods are split into uniform
//!    delegates (`n_sites`, `lhss`, `size`, …) and kind-aware variants
//!    (`is_built`, `space_kind`, `kind`).
//!
//! 2. Per-family **family** enums (`BitBasis` / `TritBasis` /
//!    `QuatBasis` / `DynDitBasis`) — switch between Default and
//!    `LargeInt` (the `LargeInt` arm vanishes when the
//!    `large-int` feature is off, so no `#[cfg]` ever appears inside
//!    a method body). Generated by [`impl_family_dispatch_enum!`].
//!
//! 3. The **outer** `SpaceInner` enum — switches between the four
//!    families. Generated by [`impl_outer_dispatch_enum!`].

/// Generate every inherent method on an inner per-size dispatch enum.
///
/// Variants are partitioned into three sets:
/// - `full` — `FullSpace` variants (always built, `SpaceKind::Full`,
///   `kind() == "full"`).
/// - `sub`  — `Subspace` variants.
/// - `sym`  — `SymBasis` variants.
///
/// All variants must take a single tuple field holding a basis-like
/// type with the named methods. Empty `full = []` is supported (the
/// `LargeInt` enums have no full-space variants).
macro_rules! impl_inner_dispatch_enum {
    (
        $Enum:ident,
        full = [$($full:ident),* $(,)?],
        sub  = [$($sub:ident),* $(,)?],
        sym  = [$($sym:ident),* $(,)?] $(,)?
    ) => {
        impl $Enum {
            /// Number of lattice sites.
            #[inline]
            pub fn n_sites(&self) -> usize {
                match self {
                    $(Self::$full(b) => b.n_sites(),)*
                    $(Self::$sub(b)  => b.n_sites(),)*
                    $(Self::$sym(b)  => b.n_sites(),)*
                }
            }

            /// Local Hilbert-space size (LHSS).
            #[inline]
            pub fn lhss(&self) -> usize {
                match self {
                    $(Self::$full(b) => b.lhss(),)*
                    $(Self::$sub(b)  => b.lhss(),)*
                    $(Self::$sym(b)  => b.lhss(),)*
                }
            }

            /// Number of basis states.
            #[inline]
            pub fn size(&self) -> usize {
                match self {
                    $(Self::$full(b) => b.size(),)*
                    $(Self::$sub(b)  => b.size(),)*
                    $(Self::$sym(b)  => b.size(),)*
                }
            }

            /// `true` iff the basis has been built. `Full*` variants
            /// are always built; `Sub*` and `Sym*` consult their inner
            /// `is_built` flag.
            #[inline]
            pub fn is_built(&self) -> bool {
                match self {
                    $(Self::$full(_) => true,)*
                    $(Self::$sub(b)  => b.is_built(),)*
                    $(Self::$sym(b)  => b.is_built(),)*
                }
            }

            /// `SpaceKind::Full` / `Sub` / `Symm` based on the variant.
            #[inline]
            pub fn space_kind(&self) -> $crate::spin::SpaceKind {
                use $crate::spin::SpaceKind;
                match self {
                    $(Self::$full(_) => SpaceKind::Full,)*
                    $(Self::$sub(_)  => SpaceKind::Sub,)*
                    $(Self::$sym(_)  => SpaceKind::Symm,)*
                }
            }

            /// One of `"full"`, `"subspace"`, or `"symmetric"`.
            #[inline]
            pub fn kind(&self) -> &'static str {
                match self {
                    $(Self::$full(_) => "full",)*
                    $(Self::$sub(_)  => "subspace",)*
                    $(Self::$sym(_)  => "symmetric",)*
                }
            }

            /// `true` iff this is a `Sym*` variant (symmetry-reduced
            /// subspace).
            #[inline]
            pub fn is_symmetric(&self) -> bool {
                match self {
                    $(Self::$full(_) => false,)*
                    $(Self::$sub(_)  => false,)*
                    $(Self::$sym(_)  => true,)*
                }
            }

            /// Look up the index of a basis state given as a per-site
            /// occupation byte slice.
            #[inline]
            pub fn index_of_bytes(&self, bytes: &[u8]) -> Option<usize> {
                use $crate::seed::{dit_seed_from_bytes, seed_from_bytes};
                use quspin_bitbasis::manip::DynamicDitManip;
                macro_rules! __index {
                    ($b:expr) => {{
                        let lhss = $b.lhss();
                        let seed = if lhss == 2 {
                            seed_from_bytes(bytes)
                        } else {
                            dit_seed_from_bytes(bytes, &DynamicDitManip::new(lhss))
                        };
                        $b.index(seed)
                    }};
                }
                match self {
                    $(Self::$full(b) => __index!(b),)*
                    $(Self::$sub(b)  => __index!(b),)*
                    $(Self::$sym(b)  => __index!(b),)*
                }
            }

            /// `i`-th basis state formatted as a bit / dit string.
            #[inline]
            pub fn state_at_str(&self, i: usize) -> String {
                match self {
                    $(Self::$full(b) => $crate::dispatch::fmt_state(b.state_at(i), b.n_sites(), b.lhss()),)*
                    $(Self::$sub(b)  => $crate::dispatch::fmt_state(b.state_at(i), b.n_sites(), b.lhss()),)*
                    $(Self::$sym(b)  => $crate::dispatch::fmt_state(b.state_at(i), b.n_sites(), b.lhss()),)*
                }
            }

            /// `i`-th basis state formatted as a decimal integer
            /// string (raw internal value, LSB = site 0).
            #[inline]
            pub fn state_at_decimal_str(&self, i: usize) -> String {
                match self {
                    $(Self::$full(b) => format!("{}", b.state_at(i)),)*
                    $(Self::$sub(b)  => format!("{}", b.state_at(i)),)*
                    $(Self::$sym(b)  => format!("{}", b.state_at(i)),)*
                }
            }

            /// Add a pure-lattice (site-permutation) symmetry element.
            ///
            /// Errors on `Full*` and `Sub*` variants — only `Sym*`
            /// variants accept symmetry insertions. The caller (the
            /// `GenericBasis` wrapper) is responsible for upstream
            /// validation (`is_built`, perm length / contents, etc.);
            /// this method only performs the variant dispatch.
            #[allow(unused_variables)]
            pub fn add_lattice(
                &mut self,
                grp_char: ::num_complex::Complex<f64>,
                perm: &[usize],
            ) -> Result<(), ::quspin_types::QuSpinError> {
                use ::quspin_types::QuSpinError;
                match self {
                    $(Self::$full(_) => Err(QuSpinError::ValueError(format!(
                        "add_lattice requires a Sym* variant on {}",
                        stringify!($Enum),
                    ))),)*
                    $(Self::$sub(_) => Err(QuSpinError::ValueError(format!(
                        "add_lattice requires a Sym* variant on {}",
                        stringify!($Enum),
                    ))),)*
                    $(Self::$sym(b) => b.add_symmetry(
                        grp_char,
                        $crate::SymElement::lattice(perm),
                    ),)*
                }
            }
        }
    };
}

/// Generate every inherent method on a family-level dispatch enum
/// (`BitBasis` / `TritBasis` / `QuatBasis` /
/// `DynDitBasis`). The two arms — `Default` (always present) and
/// `LargeInt` (gated behind the `large-int` feature) — both delegate
/// to their inner enum.
///
/// The macro emits two flavors based on whether the `large-int`
/// feature is enabled, ensuring no `#[cfg]` arm appears inside any
/// match expression.
macro_rules! impl_family_dispatch_enum {
    ($Enum:ident) => {
        impl $Enum {
            #[inline]
            pub fn n_sites(&self) -> usize {
                match self {
                    Self::Default(inner) => inner.n_sites(),
                    #[cfg(feature = "large-int")]
                    Self::LargeInt(inner) => inner.n_sites(),
                }
            }

            #[inline]
            pub fn lhss(&self) -> usize {
                match self {
                    Self::Default(inner) => inner.lhss(),
                    #[cfg(feature = "large-int")]
                    Self::LargeInt(inner) => inner.lhss(),
                }
            }

            #[inline]
            pub fn size(&self) -> usize {
                match self {
                    Self::Default(inner) => inner.size(),
                    #[cfg(feature = "large-int")]
                    Self::LargeInt(inner) => inner.size(),
                }
            }

            #[inline]
            pub fn is_built(&self) -> bool {
                match self {
                    Self::Default(inner) => inner.is_built(),
                    #[cfg(feature = "large-int")]
                    Self::LargeInt(inner) => inner.is_built(),
                }
            }

            #[inline]
            pub fn space_kind(&self) -> $crate::spin::SpaceKind {
                match self {
                    Self::Default(inner) => inner.space_kind(),
                    #[cfg(feature = "large-int")]
                    Self::LargeInt(inner) => inner.space_kind(),
                }
            }

            #[inline]
            pub fn kind(&self) -> &'static str {
                match self {
                    Self::Default(inner) => inner.kind(),
                    #[cfg(feature = "large-int")]
                    Self::LargeInt(inner) => inner.kind(),
                }
            }

            #[inline]
            pub fn is_symmetric(&self) -> bool {
                match self {
                    Self::Default(inner) => inner.is_symmetric(),
                    #[cfg(feature = "large-int")]
                    Self::LargeInt(inner) => inner.is_symmetric(),
                }
            }

            #[inline]
            pub fn index_of_bytes(&self, bytes: &[u8]) -> Option<usize> {
                match self {
                    Self::Default(inner) => inner.index_of_bytes(bytes),
                    #[cfg(feature = "large-int")]
                    Self::LargeInt(inner) => inner.index_of_bytes(bytes),
                }
            }

            #[inline]
            pub fn state_at_str(&self, i: usize) -> String {
                match self {
                    Self::Default(inner) => inner.state_at_str(i),
                    #[cfg(feature = "large-int")]
                    Self::LargeInt(inner) => inner.state_at_str(i),
                }
            }

            #[inline]
            pub fn state_at_decimal_str(&self, i: usize) -> String {
                match self {
                    Self::Default(inner) => inner.state_at_decimal_str(i),
                    #[cfg(feature = "large-int")]
                    Self::LargeInt(inner) => inner.state_at_decimal_str(i),
                }
            }

            #[inline]
            pub fn add_lattice(
                &mut self,
                grp_char: ::num_complex::Complex<f64>,
                perm: &[usize],
            ) -> Result<(), ::quspin_types::QuSpinError> {
                match self {
                    Self::Default(inner) => inner.add_lattice(grp_char, perm),
                    #[cfg(feature = "large-int")]
                    Self::LargeInt(inner) => inner.add_lattice(grp_char, perm),
                }
            }
        }
    };
}

pub(crate) use impl_family_dispatch_enum;
pub(crate) use impl_inner_dispatch_enum;
